[package]
name = "OG-NMI"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0"}
serde_json = "1.0"
strum = "0.27.2"
strum_macros = "0.27.2"
